// ClientOld/src/app/ui/nav/search-menu/search-menu.component.ts
import { Component, ViewChild, afterNextRender } from '@angular/core';
import { Router, NavigationEnd } from '@angular/router';
import { NgIcon, provideIcons } from "@ng-icons/core";
import { remixSearchEyeLine } from "@ng-icons/remixicon";
import { NgxFloatUiContentComponent, NgxFloatUiModule } from "ngx-float-ui";
import { DEFAULT_SLOGANS } from "$models/util";
import { FormControl, FormGroup, ReactiveFormsModule } from "@angular/forms";

@Component({
    selector: 'app-search-menu',
    standalone: true,
    imports: [
        NgIcon,
        ReactiveFormsModule,
        NgxFloatUiModule,
    ],
    viewProviders: [provideIcons({remixSearchEyeLine})],
    templateUrl: './search-menu.component.html',
    styleUrl: './search-menu.component.css'
})
export class SearchMenuComponent {
    @ViewChild(NgxFloatUiContentComponent) searchMenu!: NgxFloatUiContentComponent;
    currSlogan = DEFAULT_SLOGANS[Math.floor(Math.random() * DEFAULT_SLOGANS.length)];
    searchForm = new FormGroup({
        query: new FormControl(''),
    });

    constructor(private router: Router) {
        afterNextRender(() => {
            this.router.events.subscribe((event) => {
                if (event instanceof NavigationEnd) {
                    this.searchMenu.hide();
                }
            });
        });
    }
}

<div class="w-full relative">
    <button
        class="hidden md:flex w-11/12 h-[36px] mx-auto items-center justify-center rounded-xl border-2 border-x-transparent border-t-transparent border-zinc-300 bg-zinc-300 bg-opacity-40 backdrop-blur py-1 text-white"
        [floatUi]="searchMenu"
        [hideOnScroll]="true"
        [hideOnClickOutside]="true"
        [disableStyle]="true"
        [preventOverflow]="true"
    >
        <span class="mr-2 relative top-0.5"><ng-icon name="remixSearchEyeLine" size="18px" /></span>
        <span class="text-xs">{{ currSlogan }}</span>
    </button>

    <float-ui-content #searchMenu>
        <div class="absolute -top-[36px] overflow-hidden bg-zinc-300 dark:bg-zinc-600 w-full h-[350px] rounded-xl border border-white border-opacity-25">
            <form [formGroup]="searchForm">
                <div class="flex items-center bg-zinc-400 dark:bg-zinc-500 border-b-2 border-white">
                    <span class="pl-4 relative top-[0.1675rem]"><ng-icon name="remixSearchEyeLine" size="18px" /></span>
                    <input
                        id="search-query"
                        title="Search Offprint..."
                        type="text"
                        class="bg-transparent placeholder-zinc-600 dark:placeholder-zinc-300 w-full text-sm py-2.5 focus:ring-0 focus:border-transparent"
                        [placeholder]="currSlogan"
                        [formControlName]="'query'"
                    />
                </div>
            </form>
        </div>
    </float-ui-content>
</div>

// Client/src/lib/ui/nav/SearchMenu.svelte
<script lang="ts">
    import { DEFAULT_SLOGANS } from "$lib/models/util";

    let currSlogan = DEFAULT_SLOGANS[Math.floor(Math.random() * DEFAULT_SLOGANS.length)];
</script>

<div class="w-full relative">
    <button
        class="hidden md:flex w-11/12 h-[36px] mx-auto items-center justify-center rounded-xl border-2 border-x-transparent border-t-transparent border-zinc-300 bg-zinc-300 bg-opacity-40 backdrop-blur py-1 text-white"
    >
        <span class="mr-2 relative top-0.5"><ng-icon name="remixSearchEyeLine" size="18px" /></span>
        <span class="text-xs">{currSlogan}</span>
    </button>
</div>
