// Client/src/app/pages/auth/log-in/log-in.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ReactiveFormsModule, FormGroup, FormControl, Validators } from "@angular/forms";
import { NgIconComponent, provideIcons } from "@ng-icons/core";
import { lucideLogIn } from "@ng-icons/lucide";
import { TextFieldComponent } from "$ui/forms";
import { ButtonComponent } from "$ui/util";
import { Router, RouterLink } from "@angular/router";
import { Select, Store } from "@ngxs/store";
import { Observable, take, withLatestFrom } from "rxjs";
import { AuthState, AuthModel, AuthActions } from "$state/auth";
import { remixMailCheckLine, remixUserForbidLine } from "@ng-icons/remixicon";
import { Meta, Title } from "@angular/platform-browser";
import { generateTags } from "$util/meta";

@Component({
    selector: 'app-log-in',
    standalone: true,
    imports: [CommonModule, ReactiveFormsModule, TextFieldComponent, ButtonComponent, NgIconComponent, RouterLink],
    viewProviders: [provideIcons({ lucideLogIn, remixMailCheckLine, remixUserForbidLine  })],
    templateUrl: './log-in.component.html',
    styleUrl: './log-in.component.css'
})
export class LogInComponent implements OnInit {
    @Select(AuthState) auth$!: Observable<AuthModel>;
    showUnavailableActionPrompt = false;

    loginForm = new FormGroup({
        email: new FormControl('', [Validators.required, Validators.email]),
        password: new FormControl('', [Validators.required, Validators.min(8)]),
    });

    constructor(private store: Store, private router: Router, private title: Title, private meta: Meta) {}

    ngOnInit() {
        this.auth$.pipe(take(1)).subscribe(value => {
            if (value.account) {
                this.showUnavailableActionPrompt = true;
            }
        });

        this.title.setTitle("Log In — Offprint");
        this.meta.addTags(generateTags("Log In", "Log In To Your Offprint Account", "website", "https://offprint.cafe/auth/log-in", "/images/offprint_icon.png"))
    }

    get email() { return this.loginForm.controls['email'].value; }
    get password() { return this.loginForm.controls['password'].value; }

    onSubmit() {
        if (this.loginForm.valid) {
            const loginFormValue = {
                email: this.email!,
                password: this.password!,
            }
            this.store.dispatch(new AuthActions.LogIn(loginFormValue))
                .pipe(withLatestFrom(this.auth$))
                .subscribe(([_, auth]) => {
                    if (auth.token) {
                        console.log("navigating...");
                        this.router.navigate(['/auth/switch-profile']).then(() => this.loginForm.reset());
                    } else {
                        this.router.navigate(['/auth/check-inbox']).then(() => this.loginForm.reset());
                    }
                });
        }
    }
}

<div
    class="flex flex-col items-center justify-center pt-[55px] md:pt-0 w-full h-[100svh] md:h-screen bg-cover bg-center"
    style="background-image: url('/assets/images/mountains.jpg')"
>
    <div class="bg-zinc-200/75 dark:bg-zinc-700/75 backdrop-blur-lg md:rounded-xl max-w-md p-6 md:p-12 w-full h-full md:h-fit">
        @if (showUnavailableActionPrompt) {
            <div class="flex flex-col items-center justify-center">
                <h1 class="text-3xl">Whoops!</h1>
                <span class="text-zinc-500 dark:text-zinc-400 text-lg font-bold text-center pb-8" style="font-family: var(--header-text);">
                    Looks like you've taken the wrong turn.
                </span>
                <ng-icon name="remixUserForbidLine" size="150px" />
                <span class="text-zinc-500 dark:text-zinc-400 text-lg font-bold text-center pt-8" style="font-family: var(--header-text);">
                    You're already logged in!
                </span>
            </div>
        } @else {
            <div class="flex flex-col items-center justify-center pb-4">
                <h1 class="text-3xl">Welcome back!</h1>
                <span class="text-zinc-500 dark:text-zinc-400 text-lg font-bold" style="font-family: var(--header-text);">
                    We're so glad you're here.
                </span>
            </div>
            <form [formGroup]="loginForm" (ngSubmit)="onSubmit()" class="flex flex-col">
                <app-text-field
                    [id]="'email'"
                    [label]="'Email Address'"
                    [type]="'email'"
                    [placeholder]="'somebody@example.net'"
                    [autocomplete]="'email'"
                    formControlName="email"
                />
                <div class="my-1.5"><!--spacer--></div>
                <app-text-field
                    [id]="'password'"
                    [label]="'Password'"
                    [type]="'password'"
                    [placeholder]="'••••••••••••'"
                    [autocomplete]="'current-password'"
                    formControlName="password"
                />
                <a class="text-zinc-500 dark:text-zinc-400 text-sm pt-2 hover:underline">Forgot your password?</a>
                <div class="my-3"><!--spacer--></div>
                <app-button
                    [id]="'login-button'"
                    [title]="'Log In'"
                    [type]="'submit'"
                    [kind]="'primary'"
                    [fullWidth]="true"
                >
                    <span class="button-icon"><ng-icon name="lucideLogIn" /></span>
                    <span class="button-text">Log In</span>
                </app-button>
                <a class="text-center w-full pt-4 text-zinc-500 dark:text-zinc-400 text-sm hover:underline" [routerLink]="['/auth/sign-up']">
                    Looking to join? Sign up today!
                </a>
            </form>
        }
    </div>
</div>

// Client/src/routes/(auth)/log-in/+page.svelte
<script lang="ts">
    import type { ActionData } from "./$types";
    import { TextField } from "$lib/ui/forms";
    import { Button } from "$lib/ui/util";
	import { onMount } from "svelte";
    import { RiLoginCircleLine, RiUserForbidLine } from "svelte-remixicon";
    import { auth } from "$lib/state/auth.state";
	import { enhance } from "$app/forms";
    import toast from "svelte-french-toast";
	import { goto } from "$app/navigation";

    export let form: ActionData;
    let showUnavailableActionPrompt = false;

    onMount(() => {
        if ($auth.account) {
            showUnavailableActionPrompt = true;
        }
    });

    $: {
        if (form?.error) {
            toast.error(form!.error.message, { duration: 5000 });
        } else if (form?.account) {
            const account = form!.account;

            $auth.account = account;
            $auth.token = account.token;

            goto("/switch-profile");
        }
    }
</script>

<svelte:head>
	<title>Log In &mdash; Offprint</title>
	<!-- Primary Meta Tags -->
	<meta name="title" content="Offprint" />
	<meta name="description" content="For The Stories Left Untold" />

	<!-- Open Graph / Facebook -->
	<meta property="og:type" content="website" />
	<meta property="og:url" content="https://offprint.cafe/" />
	<meta property="og:title" content="Offprint" />
	<meta
		property="og:description"
		content="For The Stories Left Untold"
	/>
	<meta property="og:image" content="/images/offprint_icon.png" />

	<!-- Twitter -->
	<meta property="twitter:card" content="summary_large_image" />
	<meta property="twitter:url" content="https://offprint.cafe/" />
	<meta property="twitter:title" content="Offprint" />
	<meta
		property="twitter:description"
		content="For The Stories Left Untold"
	/>
	<meta property="twitter:image" content="/images/offprint_icon.png" />
</svelte:head>

<div class="bg-zinc-200/75 dark:bg-zinc-700/75 backdrop-blur-lg md:rounded-xl max-w-md p-6 md:p-12 w-full h-full md:h-fit">
    {#if showUnavailableActionPrompt}
        <div class="flex flex-col items-center justify-center">
            <h1 class="text-3xl">Whoops!</h1>
            <span class="text-zinc-500 dark:text-zinc-400 text-lg font-bold text-center pb-8" style="font-family: var(--header-text);">
                Looks like you've taken the wrong turn.
            </span>
            <RiUserForbidLine size="150px" />
            <span class="text-zinc-500 dark:text-zinc-400 text-lg font-bold text-center pt-8" style="font-family: var(--header-text);">
                You're already logged in!
            </span>
        </div>
    {:else}
        <div class="flex flex-col items-center justify-center pb-4">
            <h1 class="text-3xl">Welcome back!</h1>
            <span class="text-zinc-500 dark:text-zinc-400 text-lg font-bold" style="font-family: var(--header-text);">
                We're so glad you're here.
            </span>
        </div>
        <form
            class="flex flex-col"
            method="post"
            use:enhance
        >
            <TextField
                name="email"
                label="Email Address"
                type="email"
                placeholder="somebody@example.net"
                autocomplete="email"
                required
                value={null}
            />
            <div class="my-1.5"></div>
            <TextField
                name="password"
                label="Password"
                type="password"
                placeholder="•••••••••••"
                autocomplete="current-password"
                required
                value={null}
            />
            <a class="text-zinc-500 dark:text-zinc-400 text-sm pt-2 hover:underline" href="/forgot-password">Forgot your password?</a>
            <div class="my-3"></div>
            <Button
                id="login-button"
                title="Log In"
                type="submit"
                kind="primary"
                fullWidth
            >
                <span class="button-icon"><RiLoginCircleLine /></span>
                <span class="button-text">Log In</span>
            </Button>
            <a class="text-center w-full pt-4 text-zinc-500 dark:text-zinc-400 text-sm hover:underline" href="/sign-up">
                Looking to join? Sign up today!
            </a>
        </form>
    {/if}
</div>
