// ClientOld/src/lib/ui/nav/guide/MainPanel.svelte
<script lang="ts">
    import { IconFeather, IconCoffee, IconEyeHeart, IconBookUpload, IconLink, IconUsersGroup, IconArrowsDoubleNeSw, IconAdjustments, IconLogout2, IconChevronRight } from "@tabler/icons-svelte";
    import { auth } from "$lib/state/auth.state";
    import { slugify } from "$lib/util/functions";
	import { createEventDispatcher } from "svelte";

    const dispatch = createEventDispatcher();
</script>

<div class="flex flex-col w-full overflow-hidden rounded-xl bg-zinc-400/25 dark:bg-zinc-500/25">
    <div class="h-[75px] overflow-hidden w-full relative bg-accent">
        {#if $auth.currProfile?.bannerArt}
            <img src={$auth.currProfile?.bannerArt} class="h-full w-full object-cover" alt="profile avatar" />
        {/if}
    </div>
    <div class="w-full flex items-center p-2">
        <div class="mr-2 w-[60px] h-[60px] overflow-hidden rounded-full border-2 border-white">
            <img src={$auth.currProfile?.avatar} class="w-full h-full object-cover" alt="avatar" />
        </div>
        <div class="flex flex-1 flex-col">
            <h1 class="max-w-[270px] truncate text-2xl">
                <a class="hover:underline" href="/profile/{$auth.currProfile?.id}/{slugify($auth.currProfile?.username)}">
                    {$auth.currProfile?.username}
                </a>
            </h1>
            <!--TODO: add role badges-->
        </div>
    </div>
    <div class="all-small-caps flex w-full border-t border-zinc-400 text-lg font-bold dark:border-zinc-500 font-header">
        <a
            class="flex h-[65px] w-1/3 flex-col text-default hover:text-default hover:no-underline items-center justify-center pt-0.5 transition hover:bg-zinc-300 hover:dark:bg-zinc-600"
            href="/profile/{$auth.currProfile?.id}/{slugify($auth.currProfile?.username)}/works"
        >
            <div class="flex items-center relative top-2">
                <span class="relative -top-1"><IconFeather size="18px" /></span>
                <span class="relative -top-1 ml-1 text-xl">0</span>
            </div>
            <span class="relative -top-1">Works</span>
        </a>
        <a
            class="flex h-[65px] w-1/3 flex-col items-center justify-center text-default hover:text-default hover:no-underline border-l border-r border-zinc-400 pt-0.5 transition hover:bg-zinc-300 dark:border-zinc-500 hover:dark:bg-zinc-600"
            href="/profile/{$auth.currProfile?.id}/{slugify($auth.currProfile?.username)}/blogs"
        >
            <div class="flex items-center relative top-2">
                <span class="relative -top-1"><IconCoffee size="18px" /></span>
                <span class="relative -top-1 ml-1 text-xl">0</span>
            </div>
            <span class="relative -top-1.5">Blogs</span>
        </a>
        <a
            class="flex h-[65px] w-1/3 flex-col items-center justify-center text-default hover:text-default hover:no-underline pt-0.5 transition hover:bg-zinc-300 hover:dark:bg-zinc-600"
            href="/profile/{$auth.currProfile?.id}/{slugify($auth.currProfile?.username)}/followers"
        >
            <div class="flex items-center relative top-2">
                <span class="relative -top-1"><IconEyeHeart size="18px" /></span>
                <span class="relative -top-1 ml-1 text-xl">0</span>
            </div>
            <span class="relative -top-1.5">Follows</span>
        </a>
    </div>
</div>
<div class="my-2" />
<div
    class="flex w-full flex-col overflow-hidden rounded-xl bg-zinc-400/25 dark:bg-zinc-500/25"
>
    <a
        class="flex items-center border-b border-zinc-400 text-default hover:text-default hover:no-underline px-4 py-3 transition hover:bg-zinc-300/75 dark:border-zinc-500 dark:hover:bg-zinc-600/75"
        href="/profile/{$auth.currProfile?.id}/{slugify($auth.currProfile?.username)}/works/new"
    >
        <span class="relative mr-2">
            <IconBookUpload size="24px" />
        </span>
        <span class="flex-1 relative top-0.5">Create a New Work</span>
        <span class="relative text-zinc-400 dark:text-zinc-500">
            <IconLink size="20px" />
        </span>
    </a>
    <a
        class="flex items-center text-default hover:text-default hover:no-underline px-4 py-3 transition hover:bg-zinc-300/75 dark:hover:bg-zinc-600/75"
        href="/profile/{$auth.currProfile?.id}/{slugify($auth.currProfile?.username)}/blogs/new"
    >
        <span class="relative mr-2">
            <IconCoffee size="24px" />
        </span>
        <span class="flex-1 relative top-0.5">Create a New Blog</span>
        <span class="relative text-zinc-400 dark:text-zinc-500">
            <IconLink size="20px" />
        </span>
    </a>
</div>
<div class="my-2" />
<div
    class="flex w-full flex-col overflow-hidden rounded-xl bg-zinc-400/25 dark:bg-zinc-500/25"
>
    <a
        class="flex items-center px-4 py-3 text-default hover:text-default hover:no-underline transition hover:bg-zinc-300/75 dark:hover:bg-zinc-600/75"
        href="/switch-profile"
    >
        <span class="relative mr-2">
            <IconUsersGroup size="24px" />
        </span>
        <span class="flex-1 relative top-0.5">Switch Profile</span>
        <span class="relative text-zinc-400 dark:text-zinc-500">
            <IconArrowsDoubleNeSw size="20px" />
        </span>
    </a>
</div>
<div class="my-2" />
<div
    class="flex w-full flex-col overflow-hidden rounded-xl bg-zinc-400/25 dark:bg-zinc-500/25"
>
    <a
        class="flex items-center px-4 py-3 transition text-default hover:text-default hover:no-underline hover:bg-zinc-300/75 dark:hover:bg-zinc-600/75 border-b border-zinc-400 dark:border-zinc-500"
        href="/settings"
    >
        <span class="relative mr-2">
            <IconAdjustments size="24px" />
        </span>
        <span class="flex-1 relative top-0.5">Settings</span>
        <span class="relative text-zinc-400 dark:text-zinc-500">
            <IconLink size="20px" />
        </span>
    </a>
    <button
        class="flex items-center px-4 py-3 transition hover:bg-zinc-300/75 dark:hover:bg-zinc-600/75"
        on:click={() => dispatch('logout')}
    >
        <span class="relative mr-2">
            <IconLogout2 size="24px" />
        </span>
        <span class="flex-1 text-left relative top-0.5">Log Out</span>
        <span class="relative text-zinc-400 dark:text-zinc-500">
            <IconChevronRight width="20px" height="20px" />
        </span>
    </button>
</div>

// Client/src/app/ui/nav/user-menu/panels/main-panel/main-panel.component.ts
import { Component, EventEmitter, Output } from "@angular/core";
import { NgIconComponent, provideIcons } from "@ng-icons/core";
import { AsyncPipe, NgOptimizedImage, NgIf } from "@angular/common";
import {
    remixArrowDownSLine,
    remixArrowLeftRightLine,
    remixArrowRightSLine,
    remixArrowUpSLine,
    remixBook2Line,
    remixCloseLine,
    remixCupLine,
    remixEyeLine,
    remixLinksLine,
    remixLogoutBoxLine,
    remixQuillPenLine,
    remixSettings6Line,
} from "@ng-icons/remixicon";
import { Select, Store } from "@ngxs/store";
import { AuthActions, AuthState } from "$state/auth";
import { Observable, take } from "rxjs";
import { Profile } from "$models/accounts";
import { Router, RouterLink } from "@angular/router";
import { SlugifyPipe } from "$util/pipes";

@Component({
    selector: "app-main-panel",
    standalone: true,
    imports: [NgIconComponent, NgOptimizedImage, AsyncPipe, NgIf, RouterLink, SlugifyPipe],
    viewProviders: [
        provideIcons({
            remixQuillPenLine,
            remixCupLine,
            remixEyeLine,
            remixBook2Line,
            remixArrowLeftRightLine,
            remixLogoutBoxLine,
            remixLinksLine,
            remixArrowDownSLine,
            remixArrowUpSLine,
            remixArrowRightSLine,
            remixSettings6Line,
            remixCloseLine,
        }),
    ],
    templateUrl: "./main-panel.component.html",
    styleUrl: "./main-panel.component.css",
})
export class MainPanelComponent {
    @Select(AuthState.profiles) profiles$!: Observable<Profile[]>;
    @Select(AuthState.currProfile) currProfile$!: Observable<Profile>;
    @Output() onClickSettings = new EventEmitter();
    @Output() onClickLogOut = new EventEmitter();
    showSwitchProfile = false;

    constructor(private store: Store) {
    }

    selectProfile(id: string) {
        this.store.dispatch(new AuthActions.SelectProfile(id))
            .pipe(take(1))
            .subscribe(() => {
                this.showSwitchProfile = false;
            });
    }
}

<div
    class="flex w-full flex-col overflow-hidden rounded-xl bg-zinc-400/25 backdrop-blur-lg dark:bg-zinc-500/25"
    *ngIf="currProfile$ | async as profile"
>
    <div class="h-[75px] w-full" style="background-color: rgb(var(--accent))">
        <!--banner-->
    </div>
    <div class="flex w-full items-center p-2">
        <div class="mr-2 overflow-hidden rounded-full border border-zinc-300">
            <img [ngSrc]="profile.avatar" width="60" height="60" alt="avatar" />
        </div>
        <div class="flex flex-1 flex-col">
            <h1 class="max-w-[270px] truncate text-2xl">
                <a class="hover:underline" [routerLink]="['/profile', profile.id, profile.username | slugify]">
                    {{ profile.username }}
                </a>
            </h1>
            <!--TODO: add role badges-->
        </div>
    </div>
    <div
        class="all-small-caps flex w-full border-t border-zinc-400 text-lg font-bold dark:border-zinc-500"
        style="font-family: var(--header-text)"
    >
        <a
            class="flex h-[65px] w-1/3 flex-col items-center justify-center pt-0.5 transition hover:bg-zinc-300 hover:dark:bg-zinc-600"
        >
            <div class="relative top-2">
                <span><ng-icon name="remixQuillPenLine" /></span>
                <span class="relative -top-1 ml-1 text-xl">0</span>
            </div>
            <span class="relative -top-1.5">Works</span>
        </a>
        <a
            class="flex h-[65px] w-1/3 flex-col items-center justify-center border-l border-r border-zinc-400 pt-0.5 transition hover:bg-zinc-300 dark:border-zinc-500 hover:dark:bg-zinc-600"
        >
            <div class="relative top-2">
                <span><ng-icon name="remixCupLine" /></span>
                <span class="relative -top-1 ml-1 text-xl">0</span>
            </div>
            <span class="relative -top-1.5">Blogs</span>
        </a>
        <a
            class="flex h-[65px] w-1/3 flex-col items-center justify-center pt-0.5 transition hover:bg-zinc-300 hover:dark:bg-zinc-600"
        >
            <div class="relative top-2">
                <span><ng-icon name="remixEyeLine" /></span>
                <span class="relative -top-1 ml-1 text-xl">0</span>
            </div>
            <span class="relative -top-1.5">Follows</span>
        </a>
    </div>
</div>
<div class="my-2"><!--spacer--></div>
<div
    class="flex w-full flex-col overflow-hidden rounded-xl bg-zinc-400/25 backdrop-blur-lg dark:bg-zinc-500/25"
>
    <a
        class="flex items-center border-b border-zinc-400 px-4 pb-1.5 pt-2 transition hover:bg-zinc-300/75 dark:border-zinc-500 dark:hover:bg-zinc-600/75"
    >
        <span class="relative top-0.5 mr-2"
            ><ng-icon name="remixBook2Line" size="24px"
        /></span>
        <span class="flex-1">Create New Work</span>
        <span class="relative top-0.5 text-zinc-400 dark:text-zinc-500"
            ><ng-icon name="remixLinksLine" size="20px"
        /></span>
    </a>
    <a
        class="flex items-center px-4 pb-1.5 pt-2 transition hover:bg-zinc-300/75 dark:hover:bg-zinc-600/75"
    >
        <span class="relative top-0.5 mr-2"
            ><ng-icon name="remixCupLine" size="24px"
        /></span>
        <span class="flex-1">Create New Blog</span>
        <span class="relative top-0.5 text-zinc-400 dark:text-zinc-500"
            ><ng-icon name="remixLinksLine" size="20px"
        /></span>
    </a>
</div>
<div class="my-2"><!--spacer--></div>
<div
    class="flex w-full flex-col overflow-hidden rounded-xl bg-zinc-400/25 backdrop-blur-lg dark:bg-zinc-500/25"
>
    <button
        class="flex items-center px-4 pb-1.5 pt-2 transition hover:bg-zinc-300/75 dark:hover:bg-zinc-600/75"
        (click)="showSwitchProfile = !showSwitchProfile"
    >
        <span class="relative top-0.5 mr-2"
            ><ng-icon name="remixArrowLeftRightLine" size="24px"
        /></span>
        <span class="flex-1 text-left">Switch Profile</span>
        <span class="relative top-0.5 text-zinc-400 dark:text-zinc-500">
            @if (showSwitchProfile) {
                <ng-icon name="remixArrowUpSLine" size="20px" />
            } @else {
                <ng-icon name="remixArrowDownSLine" size="20px"/>
            }
        </span>
    </button>
    @if (showSwitchProfile) {
        <div class="flex items-center justify-center pb-3">
            @for (profile of profiles$ | async; track profile.id) {
                <button
                    class="flex flex-col items-center rounded-xl p-4 mx-1 w-[100px] h-[100px] hover:bg-zinc-300 dark:hover:bg-zinc-600 transition"
                    (click)="selectProfile(profile.id)"
                >
                    <img class="rounded-full border-2 object-cover" [ngSrc]="profile.avatar" width="50" height="50" />
                    <span class="pt-1 all-small-caps font-bold text-sm truncate max-w-[80px]">
                        {{ profile.username }}
                    </span>
                </button>
            }
        </div>
    }
</div>
<div class="my-2"><!--spacer--></div>
<div
    class="flex w-full flex-col overflow-hidden rounded-xl bg-zinc-400/25 backdrop-blur-lg dark:bg-zinc-500/25"
>
    <button
        class="flex items-center border-b border-zinc-400 px-4 pb-1.5 pt-2 transition hover:bg-zinc-300/75 dark:border-zinc-500 dark:hover:bg-zinc-600/75"
        (click)="onClickSettings.emit()"
    >
        <span class="relative top-0.5 mr-2"
            ><ng-icon name="remixSettings6Line" size="24px"
        /></span>
        <span class="flex-1 text-left">Quick Settings</span>
        <span class="relative top-0.5 text-zinc-400 dark:text-zinc-500"
            ><ng-icon name="remixArrowRightSLine" size="20px"
        /></span>
    </button>
    <button
        class="flex items-center px-4 pb-1.5 pt-2 transition hover:bg-zinc-300/75 dark:hover:bg-zinc-600/75"
        (click)="onClickLogOut.emit()"
    >
        <span class="relative top-0.5 mr-2"
            ><ng-icon name="remixLogoutBoxLine" size="24px"
        /></span>
        <span class="flex-1 text-left">Log Out</span>
        <span class="relative top-0.5 text-zinc-400 dark:text-zinc-500"
            ><ng-icon name="remixArrowRightSLine" size="20px"
        /></span>
    </button>
</div>
