// Client/src/app/pages/auth/sign-up/sign-up.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormControl, FormGroup, ReactiveFormsModule, Validators } from "@angular/forms";
import { TextFieldComponent } from "$ui/forms";
import { ButtonComponent } from "$ui/util";
import { NgIconComponent, provideIcons } from "@ng-icons/core";
import { Router, RouterLink } from "@angular/router";
import { remixMailCheckLine, remixUserForbidLine, remixUserAddLine } from "@ng-icons/remixicon";
import { Select, Store } from "@ngxs/store";
import { AuthModel, AuthState, AuthActions } from "$state/auth";
import { Observable, take } from "rxjs";
import { RegisterForm } from "$models/accounts";

@Component({
    selector: 'app-sign-up',
    standalone: true,
    imports: [CommonModule, ReactiveFormsModule, TextFieldComponent, ButtonComponent, NgIconComponent, RouterLink],
    viewProviders: [provideIcons({ remixUserAddLine, remixMailCheckLine, remixUserForbidLine })],
    templateUrl: './sign-up.component.html',
    styleUrl: './sign-up.component.css'
})
export class SignUpComponent implements OnInit {
    @Select(AuthState) auth$!: Observable<AuthModel>;
    showUnavailableActionPrompt = false;

    registerForm = new FormGroup({
        email: new FormControl('', [Validators.required, Validators.email]),
        password: new FormControl('', [Validators.required, Validators.min(8)]),
        repeatPassword: new FormControl('', [Validators.required, Validators.min(8)]),
        ageCheck: new FormControl(false, [Validators.required, Validators.requiredTrue]),
        termsAgree: new FormControl(false, [Validators.required, Validators.requiredTrue]),
    });

    constructor(private store: Store, private router: Router) {}

    ngOnInit() {
        this.auth$.pipe(take(1)).subscribe(value => {
            if (value.account) {
                this.showUnavailableActionPrompt = true;
            }
        });
    }

    get email() { return this.registerForm.controls['email']; }
    get password() { return this.registerForm.controls['password']; }
    get repeatPassword() { return this.registerForm.controls['repeatPassword']; }
    get ageCheck() { return this.registerForm.controls['ageCheck']; }
    get termsAgree() { return this.registerForm.controls['termsAgree']; }

    onSubmit() {
        if (this.registerForm.valid) {
            if (this.password !== this.repeatPassword) {
                // TODO: replace this with an actual alert pop up that isn't just the system shit
                alert('Passwords must match!');
                return;
            }

            const formInfo: RegisterForm = {
                email: this.email.value!,
                password: this.password.value!,
                ageCheck: this.ageCheck.value!,
                termsAgree: this.termsAgree.value!,
            }

            this.store.dispatch(new AuthActions.Register(formInfo))
                .subscribe(() => {
                    this.router.navigate(['/auth/check-inbox']).then(() => this.registerForm.reset());
                });
        }
    }
}

<div
    class="flex flex-col items-center justify-center pt-[55px] md:pt-0 w-full h-[100svh] md:h-screen bg-cover bg-center"
    style="background-image: url('/assets/images/mountains.jpg')"
>
    <div class="bg-zinc-200/75 dark:bg-zinc-700/75 backdrop-blur-lg md:rounded-xl max-w-md p-6 md:p-12 w-full h-full md:h-fit overflow-y-scroll">
        @if (showUnavailableActionPrompt) {
            <div class="flex flex-col items-center justify-center">
                <h1 class="text-3xl">Whoops!</h1>
                <span class="text-zinc-500 dark:text-zinc-400 text-lg font-bold text-center pb-8" style="font-family: var(--header-text);">
                    Looks like you've taken the wrong turn.
                </span>
                <ng-icon name="remixUserForbidLine" size="150px" />
                <span class="text-zinc-500 dark:text-zinc-400 text-lg font-bold text-center pt-8" style="font-family: var(--header-text);">
                    You're already logged in!
                </span>
            </div>
        } @else {
            <div class="flex flex-col items-center justify-center pb-4">
                <h1 class="text-3xl">Welcome to Offprint!</h1>
                <span class="text-zinc-500 dark:text-zinc-400 text-lg font-bold text-center" style="font-family: var(--header-text);">
                    Let's get started, shall we?
                </span>
            </div>
            <form [formGroup]="registerForm" (ngSubmit)="onSubmit()" class="flex flex-col">
                <app-text-field
                    [id]="'email'"
                    [label]="'Email Address'"
                    [type]="'email'"
                    [placeholder]="'somebody@example.net'"
                    [required]="true"
                    [autocomplete]="'email'"
                    [errorMessage]="email.dirty && email.status === 'INVALID' ? 'Enter a valid email address' : null"
                    formControlName="email"
                />
                <div class="my-1"><!--spacer--></div>
                <app-text-field
                    [id]="'password'"
                    [label]="'Password'"
                    [type]="'password'"
                    [placeholder]="'••••••••••••'"
                    [required]="true"
                    [autocomplete]="'new-password'"
                    [errorMessage]="password.dirty && password.status === 'INVALID' ? 'Needs a minimum of 8 characters' : null"
                    formControlName="password"
                />
                <div class="my-1"><!--spacer--></div>
                <app-text-field
                    [id]="'repeat-password'"
                    [label]="'Repeat Password'"
                    [type]="'password'"
                    [placeholder]="'••••••••••••'"
                    [required]="true"
                    [autocomplete]="'new-password'"
                    [errorMessage]="repeatPassword.dirty && repeatPassword.status === 'INVALID' ? 'Needs a minimum of 8 characters' : null"
                    formControlName="repeatPassword"
                />
                <label class="flex mt-4 mb-2">
                    <input
                        type="checkbox"
                        class="rounded bg-zinc-500 w-[18px] h-[18px] relative top-[0.075rem] border-0 mr-2 transition checked:bg-blue-500/75"
                        formControlName="ageCheck"
                    />
                    <span class="text-sm align-top select-none">I am 13 years of age or older</span>
                </label>
                <label class="flex mt-2 mb-4">
                    <input
                        type="checkbox"
                        class="rounded bg-zinc-500 w-[18px] h-[18px] relative top-[0.075rem] border-0 mr-2 transition checked:bg-blue-500/75"
                        formControlName="termsAgree"
                    />
                    <span class="text-sm align-top select-none">I agree to the Terms of Service, Privacy Policy, and Constitution</span>
                </label>
                <app-button
                    [id]="'sign-up-button'"
                    [title]="'Sign Up'"
                    [type]="'submit'"
                    [kind]="'primary'"
                    [fullWidth]="true"
                >
                    <span class="button-icon"><ng-icon name="remixUserAddLine" /></span>
                    <span class="button-text">Sign Up</span>
                </app-button>
                <a class="text-center w-full pt-4 text-zinc-500 dark:text-zinc-400 text-sm hover:underline" [routerLink]="['/auth/log-in']">
                    Already have an account?
                </a>
            </form>
        }
    </div>
</div>

// Client/src/routes/(auth)/sign-up/+page.svelte
<script lang="ts">
    import { TextField } from "$lib/ui/forms";
    import { Button } from "$lib/ui/util";
    import { onMount } from "svelte";
    import { auth } from "$lib/state/auth.state";
    import { RiUserAddLine, RiUserForbidLine } from "svelte-remixicon";

    let showUnavailableActionPrompt = false;

    let emailValue: string;
    let passwordValue: string;
    let repeastPasswordValue: string;

    onMount(() => {
        if ($auth.account) {
            showUnavailableActionPrompt = true;
        }
    });
</script>

<div class="bg-zinc-200/75 dark:bg-zinc-700/75 backdrop-blur-lg md:rounded-xl max-w-md p-6 md:p-12 w-full h-full md:h-fit overflow-y-scroll">
    {#if showUnavailableActionPrompt}
        <div class="flex flex-col items-center justify-center">
            <h1 class="text-3xl">Whoops!</h1>
            <span class="text-zinc-500 dark:text-zinc-400 text-lg font-bold text-center pb-8" style="font-family: var(--header-text);">
                Looks like you've taken the wrong turn.
            </span>
            <RiUserForbidLine size="150px" />
            <span class="text-zinc-500 dark:text-zinc-400 text-lg font-bold text-center pt-8" style="font-family: var(--header-text);">
                You're already logged in!
            </span>
        </div>
    {:else}
        <div class="flex flex-col items-center justify-center pb-4">
            <h1 class="text-3xl">Welcome to Offprint!</h1>
            <span class="text-zinc-500 dark:text-zinc-400 text-lg font-bold text-center" style="font-family: var(--header-text);">
                Let's get started, shall we?
            </span>
        </div>
        <form class="flex flex-col">
            <TextField
                id="email"
                label="Email Address"
                type="email"
                placeholder="somebody@example.net"
                required
                autocomplete="email"
                bind:value={emailValue}
            />
            <div class="my-1"></div>
            <TextField
                id="password"
                label="Password"
                type="password"
                placeholder="••••••••••"
                required
                autocomplete="new-password"
                bind:value={passwordValue}
            />
            <div class="my-1"></div>
            <TextField
                id="repeat-password"
                label="Repeat Password"
                type="password"
                placeholder="••••••••••"
                required
                autocomplete="new-password"
                bind:value={repeastPasswordValue}
            />
            <label class="flex mt-4 mb-2">
                <input
                    type="checkbox"
                    class="rounded bg-zinc-500 w-[18px] h-[18px] relative top-[0.075rem] border-0 mr-2 transition checked:bg-blue-500/75"
                />
                <span class="text-sm align-top select-none">I am 13 years of age or older</span>
            </label>
            <label class="flex mt-2 mb-4">
                <input
                    type="checkbox"
                    class="rounded bg-zinc-500 w-[18px] h-[18px] relative top-[0.075rem] border-0 mr-2 transition checked:bg-blue-500/75"
                />
                <!--TODO: replace these with real links-->
                <span class="text-sm align-top select-none">I agree to the Terms of Service, Privacy Policy, and Offprint Constitution</span>
            </label>
            <Button
                id="sign-up"
                title="Sign Up"
                type="submit"
                kind="primary"
                fullWidth
            >
                <span class="button-icon"><RiUserAddLine /></span>
                <span class="button-text">Sign Up</span>
            </Button>
            <a class="text-center w-full pt-4 text-zinc-500 dark:text-zinc-400 text-sm hover:underline" href="/log-in">
                Already have an account?
            </a>
        </form>
    {/if}
</div>
