// Client/src/routes/registration/sign-up/+page.svelte
<script lang="ts">
	import { createForm } from "felte";
	import { UserAddLine } from "svelte-remixicon";
	import { Checkbox, TextField } from "$lib/ui/forms";
	import { Button } from "$lib/ui/util";
	import type { RegisterForm } from "$lib/models/accounts/forms";
	import toast from "svelte-french-toast";
	import { account } from "$lib/state/account.state";
	import { goto } from "$app/navigation";

	const termsUrl =
		"https://offprint.notion.site/Terms-of-Service-131ffadce0eb4e8a947144ddc70ef89b";
	const privacyUrl =
		"https://offprint.notion.site/Privacy-Policy-f22e8ccb9e9043dca23a29a7089c72f4";
	const constitutionUrl =
		"https://offprint.notion.site/The-Offprint-Constitution-ae58c23db7264280a319d1cdfa10bc41";

	const { form, data, errors, isSubmitting } = createForm({
		onSubmit: async (values) => {
			const formInfo: RegisterForm = {
				email: values.email,
				password: values.password,
				termsAgree: values.termsAgree
			};

			const response = await fetch("/api/auth/sign-up", {
				method: "POST",
				body: JSON.stringify(formInfo),
				credentials: "include"
			});
			const data = await response.json();
			if (response.status === 200) {
				$account.account = data.account;
				$account.profiles = data.profiles;
				$account.token = data.accessToken;
				await goto("/");
			} else {
				toast.error(data.message);
			}
		},
		validate: (values) => {
			const errors = {
				email: "",
				password: "",
				repeatPassword: "",
				ageCheck: "",
				termsAgree: ""
			};
			if (!values.email || !/^[^@ \t\r\n]+@[^@ \t\r\n]+\.[^@ \t\r\n]+/.test(values.email)) {
				errors.email = `That's not a valid email address.`;
			}
			if (!values.password) {
				errors.password = `Aren't you forgetting something?`;
			}
			if (values.password && values.password.length < 8) {
				errors.password = `Passwords must be at least 8 characters long.`;
			}
			if (!values.repeatPassword || values.password !== values.repeatPassword) {
				errors.repeatPassword = `Passwords must match.`;
			}
			if (values.ageCheck === false) {
				errors.ageCheck = `You must be at least 13 years or older to join.`;
			}
			if (values.termsAgree === false) {
				errors.termsAgree = `You must agree in order to join.`;
			}
			return errors;
		}
	});
</script>

<!--TODO: check to see if a user is already logged in, if true show an error message-->

<div class="w-full h-screen flex flex-col items-center justify-center">
	<div class="form-container bg-zinc-200 dark:bg-zinc-700">
		<div class="title-block">
			<h1 class="text-4xl">You new 'round these parts?</h1>
		</div>
		<div class="content-container">
			<form use:form>
				<TextField
					name="email"
					type="email"
					title="Email address"
					placeholder="somebody@example.net"
					kind="primary"
					errorMessage={$errors.email}
				/>
				<TextField
					name="password"
					type="password"
					title="Password"
					placeholder="••••••••••"
					kind="primary"
					errorMessage={$errors.password}
				/>
				<TextField
					name="repeatPassword"
					type="password"
					title="Repeat Password"
					placeholder="••••••••••"
					kind="primary"
					errorMessage={$errors.repeatPassword}
				/>
				<div class="my-0.5" />
				<Checkbox bind:value={$data.ageCheck}
					>I am at least 13 years of age or older.</Checkbox
				>
				<Checkbox bind:value={$data.termsAgree}>
					I agree to the <a href={termsUrl} target="_blank" rel="noreferrer"
						>Terms of Service</a
					>, <a href={privacyUrl} target="_blank" rel="noreferrer">Privacy Policy</a>, and
					<a href={constitutionUrl} target="_blank" rel="noreferrer"
						>Offprint Constitution</a
					>.
				</Checkbox>
				<div class="flex items-center mt-6">
					<div class="flex-1" />
					<Button
						kind="primary"
						type="submit"
						loading={$isSubmitting}
						loadingText="Signing up..."
					>
						<UserAddLine class="button-icon" />
						<span class="button-text">Sign up</span>
					</Button>
				</div>
			</form>
		</div>
	</div>
</div>

<style lang="scss">
	div.form-container {
		@apply p-4 rounded-xl max-w-2xl lg:min-w-[42rem] mx-auto;
		box-shadow: var(--dropshadow);
		div.title-block {
			@apply text-center;
		}
	}
</style>

// Client/src/app/pages/auth/sign-up/sign-up.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormControl, FormGroup, ReactiveFormsModule, Validators } from "@angular/forms";
import { TextFieldComponent } from "$ui/forms";
import { ButtonComponent } from "$ui/util";
import { NgIconComponent, provideIcons } from "@ng-icons/core";
import { Router, RouterLink } from "@angular/router";
import { remixMailCheckLine, remixUserForbidLine, remixUserAddLine } from "@ng-icons/remixicon";
import { Select, Store } from "@ngxs/store";
import { AuthModel, AuthState, AuthActions } from "$state/auth";
import { Observable, take } from "rxjs";
import { RegisterForm } from "$models/accounts";

@Component({
    selector: 'app-sign-up',
    standalone: true,
    imports: [CommonModule, ReactiveFormsModule, TextFieldComponent, ButtonComponent, NgIconComponent, RouterLink],
    viewProviders: [provideIcons({ remixUserAddLine, remixMailCheckLine, remixUserForbidLine })],
    templateUrl: './sign-up.component.html',
    styleUrl: './sign-up.component.css'
})
export class SignUpComponent implements OnInit {
    @Select(AuthState) auth$!: Observable<AuthModel>;
    showUnavailableActionPrompt = false;

    registerForm = new FormGroup({
        email: new FormControl('', [Validators.required, Validators.email]),
        password: new FormControl('', [Validators.required, Validators.min(8)]),
        repeatPassword: new FormControl('', [Validators.required, Validators.min(8)]),
        ageCheck: new FormControl(false, [Validators.required, Validators.requiredTrue]),
        termsAgree: new FormControl(false, [Validators.required, Validators.requiredTrue]),
    });

    constructor(private store: Store, private router: Router) {}

    ngOnInit() {
        this.auth$.pipe(take(1)).subscribe(value => {
            if (value.account) {
                this.showUnavailableActionPrompt = true;
            }
        });
    }

    get email() { return this.registerForm.controls['email']; }
    get password() { return this.registerForm.controls['password']; }
    get repeatPassword() { return this.registerForm.controls['repeatPassword']; }
    get ageCheck() { return this.registerForm.controls['ageCheck']; }
    get termsAgree() { return this.registerForm.controls['termsAgree']; }

    onSubmit() {
        if (this.registerForm.valid) {
            if (this.password !== this.repeatPassword) {
                // TODO: replace this with an actual alert pop up that isn't just the system shit
                alert('Passwords must match!');
                return;
            }

            const formInfo: RegisterForm = {
                email: this.email.value!,
                password: this.password.value!,
                ageCheck: this.ageCheck.value!,
                termsAgree: this.termsAgree.value!,
            }

            this.store.dispatch(new AuthActions.Register(formInfo))
                .subscribe(() => {
                    this.router.navigate(['/auth/check-inbox']).then(() => this.registerForm.reset());
                });
        }
    }
}

<div
    class="flex flex-col items-center justify-center pt-[55px] md:pt-0 w-full h-[100svh] md:h-screen bg-cover bg-center"
    style="background-image: url('/assets/images/mountains.jpg')"
>
    <div class="bg-zinc-200/75 dark:bg-zinc-700/75 backdrop-blur-lg md:rounded-xl max-w-md p-6 md:p-12 w-full h-full md:h-fit overflow-y-scroll">
        @if (showUnavailableActionPrompt) {
            <div class="flex flex-col items-center justify-center">
                <h1 class="text-3xl">Whoops!</h1>
                <span class="text-zinc-500 dark:text-zinc-400 text-lg font-bold text-center pb-8" style="font-family: var(--header-text);">
                    Looks like you've taken the wrong turn.
                </span>
                <ng-icon name="remixUserForbidLine" size="150px" />
                <span class="text-zinc-500 dark:text-zinc-400 text-lg font-bold text-center pt-8" style="font-family: var(--header-text);">
                    You're already logged in!
                </span>
            </div>
        } @else {
            <div class="flex flex-col items-center justify-center pb-4">
                <h1 class="text-3xl">Welcome to Offprint!</h1>
                <span class="text-zinc-500 dark:text-zinc-400 text-lg font-bold text-center" style="font-family: var(--header-text);">
                    Let's get started, shall we?
                </span>
            </div>
            <form [formGroup]="registerForm" (ngSubmit)="onSubmit()" class="flex flex-col">
                <app-text-field
                    [id]="'email'"
                    [label]="'Email Address'"
                    [type]="'email'"
                    [placeholder]="'somebody@example.net'"
                    [required]="true"
                    [autocomplete]="'email'"
                    [errorMessage]="email.dirty && email.status === 'INVALID' ? 'Enter a valid email address' : null"
                    formControlName="email"
                />
                <div class="my-1"><!--spacer--></div>
                <app-text-field
                    [id]="'password'"
                    [label]="'Password'"
                    [type]="'password'"
                    [placeholder]="'••••••••••••'"
                    [required]="true"
                    [autocomplete]="'new-password'"
                    [errorMessage]="password.dirty && password.status === 'INVALID' ? 'Needs a minimum of 8 characters' : null"
                    formControlName="password"
                />
                <div class="my-1"><!--spacer--></div>
                <app-text-field
                    [id]="'repeat-password'"
                    [label]="'Repeat Password'"
                    [type]="'password'"
                    [placeholder]="'••••••••••••'"
                    [required]="true"
                    [autocomplete]="'new-password'"
                    [errorMessage]="repeatPassword.dirty && repeatPassword.status === 'INVALID' ? 'Needs a minimum of 8 characters' : null"
                    formControlName="repeatPassword"
                />
                <label class="flex mt-4 mb-2">
                    <input
                        type="checkbox"
                        class="rounded bg-zinc-500 w-[18px] h-[18px] relative top-[0.075rem] border-0 mr-2 transition checked:bg-blue-500/75"
                        formControlName="ageCheck"
                    />
                    <span class="text-sm align-top select-none">I am 13 years of age or older</span>
                </label>
                <label class="flex mt-2 mb-4">
                    <input
                        type="checkbox"
                        class="rounded bg-zinc-500 w-[18px] h-[18px] relative top-[0.075rem] border-0 mr-2 transition checked:bg-blue-500/75"
                        formControlName="termsAgree"
                    />
                    <span class="text-sm align-top select-none">I agree to the Terms of Service, Privacy Policy, and Constitution</span>
                </label>
                <app-button
                    [id]="'sign-up-button'"
                    [title]="'Sign Up'"
                    [type]="'submit'"
                    [kind]="'primary'"
                    [fullWidth]="true"
                >
                    <span class="button-icon"><ng-icon name="remixUserAddLine" /></span>
                    <span class="button-text">Sign Up</span>
                </app-button>
                <a class="text-center w-full pt-4 text-zinc-500 dark:text-zinc-400 text-sm hover:underline" [routerLink]="['/auth/log-in']">
                    Already have an account?
                </a>
            </form>
        }
    </div>
</div>
