// Client/src/app/ui/content/jumbotron/jumbotron.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-jumbotron',
  standalone: true,
    imports: [CommonModule],
  templateUrl: './jumbotron.component.html',
  styleUrl: './jumbotron.component.css'
})
export class JumbotronComponent {

}

<div class="relative w-full h-[22rem] md:h-[32rem]">
    <img src="https://images.offprint.net/blog-banners/gi03BYkC8o-4A0938CB-1399-49D4-AC57-AAB60A187DC3.jpeg" class="object-cover w-full h-full" />
    <div class="absolute bottom-0 pt-4 pb-2 flex flex-col items-center w-full bg-gradient-to-b from-transparent to-black">
        <h1 class="text-xl md:text-4xl text-white">The Brightest Star in the Night Sky</h1>
        <span class="text-lg md:text-2xl text-zinc-400 italic" style="font-family: var(--header-text);">The One About The Future</span>
        <div class="flex items-center justify-center">
            <span class="text-xl mx-0.5 text-white">•</span>
            <span class="text-xl mx-0.5 text-zinc-400">•</span>
            <span class="text-xl mx-0.5 text-zinc-400">•</span>
            <span class="text-xl mx-0.5 text-zinc-400">•</span>
            <span class="text-xl mx-0.5 text-zinc-400">•</span>
        </div>
    </div>
</div>

// Client/src/lib/ui/content/Jumbotron.svelte
<div class="relative w-full h-[16rem] md:h-[28rem]">
    <img src="https://images.offprint.net/blog-banners/gi03BYkC8o-4A0938CB-1399-49D4-AC57-AAB60A187DC3.jpeg" class="object-cover w-full h-full" />
    <div class="absolute bottom-0 pt-4 pb-2 flex flex-col items-center w-full bg-gradient-to-b from-transparent to-black">
        <h1 class="text-xl md:text-4xl text-white">The Brightest Star in the Night Sky</h1>
        <span class="text-lg md:text-2xl text-zinc-400 italic" style="font-family: var(--header-text);">The One About The Future</span>
        <div class="flex items-center justify-center">
            <span class="text-xl mx-0.5 text-white">•</span>
            <span class="text-xl mx-0.5 text-zinc-400">•</span>
            <span class="text-xl mx-0.5 text-zinc-400">•</span>
            <span class="text-xl mx-0.5 text-zinc-400">•</span>
            <span class="text-xl mx-0.5 text-zinc-400">•</span>
        </div>
    </div>
</div>
